### PR TITLE
Different method

### PR DESCRIPTION
**Pull request by Ava68**

### CODE REVIEW

**Comment by ankitksh81** [comment]
Should I use this method and implement it in C++ and then add it in the code or should I add this code ?

**Comment by Ava68** [comment]
Yes please Implement in c++ and add it

**Comment by ankitksh81** [comment]
I think the logic is similar to the one which is implemented in recursive method.

**Comment by Ava68** [comment]
ya you can say that but in this implementation, we are not using vector
in c++ or ArrayList in java... so I think its a slightly different approach
but the logic is same  😂

**Comment by ankitksh81** [comment]
Yes the logic is same.
There is no use to implement this code and add then.

**Comment by ankitksh81** [comment]
Would love if you find some interesting problems and/or interesting methods for previous problems. Do create an issue if you find so.

**Comment by Ava68** [comment]
Thanks, I'll check them out.

**Pull request closed without merging**
